config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, except: [:registrations]
    as :admin do
      get 'admins/edit' => 'admins/registrations#edit', as: 'edit_admin_registration'
      put 'admins' => 'admins/registrations#update', as: 'admin_registration'
    end
    devise_scope :admin do
      authenticated :admin do
        root to: 'administrations#index', as: :authenticated_root
      end
    end

    root controller: :index, action: :index

    get 'kontakta', to: 'kontaktas#index'

    get 'blogg', to: 'articles#all'

    resources :articles, controller: 'articles', as: 'articles', only: [:show, :new, :create, :edit, :update, :index, :destroy]

    resources :kategorier, controller: 'categories', as: 'categories', only: [:show, :new, :create, :edit, :update, :index, :destroy]

    resources :brands, controller: 'brands', only: [:new, :create, :edit, :update, :index, :destroy]

    resources :produkter, controller: 'products', as: 'products', only: [:new, :create, :edit, :update, :index, :destroy]

    get '/produkter/:id', to: 'products#show'

    resources :brands, controller: 'brands', as: 'brands', only: [:show], path: ''

end

app/controllers/administrations_controller.rb
class AdministrationsController < ApplicationController
  before_action :authenticate_admin!
  def index
  end
end

app/views/administrations/index.html.erb
<div class='header-main'>
  <h1>Welcome to administrations!</h1>
</div>
<div class='button-menu'>
  <%= link_to 'Add/edit brands', brands_path, class: 'add-button' %>
</div>
<div class='button-menu'>
  <%= link_to 'Add/edit categories', categories_path, class: 'reply-button' %>
</div>
<div class='button-menu'>
  <%= link_to 'Add/edit products', products_path, class: 'cancel-button' %>
</div>
<div class='button-menu'>
  <%= link_to 'Add/edit articles', articles_path, class: 'add-button' %>
</div>