config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, except: [:registrations]
    as :admin do
      get 'admins/edit' => 'admins/registrations#edit', as: 'edit_admin_registration'
      put 'admins' => 'admins/registrations#update', as: 'admin_registration'
    end
    devise_scope :admin do
      authenticated :admin do
        root to: 'administrations#index', as: :authenticated_root
      end
    end

    root controller: :index, action: :index

    get 'kontakta', to: 'kontaktas#index'

    get 'blogg', to: 'articles#all'

    resources :articles, controller: 'articles', as: 'articles', only: [:show, :new, :create, :edit, :update, :index, :destroy]

    resources :kategorier, controller: 'categories', as: 'categories', only: [:show, :new, :create, :edit, :update, :index, :destroy]

    resources :brands, controller: 'brands', only: [:new, :create, :edit, :update, :index, :destroy]

    resources :produkter, controller: 'products', as: 'products', only: [:new, :create, :edit, :update, :index, :destroy]

    get '/produkter/:id', to: 'products#show'

    resources :brands, controller: 'brands', as: 'brands', only: [:show], path: ''

end

app/models/product.rb
require 'nokogiri'
require 'open-uri'
require 'pry'

class Product < ApplicationRecord
  validates_presence_of :name
  validates :store_1_price, numericality: { only_float: true }, allow_blank: true
  validates :store_2_price, numericality: { only_float: true }, allow_blank: true
  validates :store_2_price, numericality: { only_float: true }, allow_blank: true
  belongs_to :brand
  belongs_to :primary_category, class_name: 'Category', optional: true
  belongs_to :secondary_category, class_name: 'Category', optional: true
  belongs_to :third_category, class_name: 'Category', optional: true
  has_one_attached :avatar
  before_update :scrape_product_price_1
  before_update :scrape_product_price_2
  before_update :scrape_product_price_3
  before_update :set_best_price

  scope :active, -> { where active: true }

  STORE_OPTIONS = [ "NetOnNet", "Sportamore", "Cdon" ]

  extend FriendlyId
  friendly_id :name, use: :slugged

  private

  def scrape_product_price_1
    link = "#{self.store_1_link}"
    html = open(link)
    doc = Nokogiri::HTML(html)
    products = doc.css('#productPurchaseBoxContainer').css('.panel-body.productColor').css('.price-big')
    self.store_1_price = products.first.children.text.delete("^0-9").to_f
  end

  def scrape_product_price_2
    if self.store_2_name?
      link = "#{self.store_2_link}"
      html = open(link)
      doc = Nokogiri::HTML(html)
      products = doc.css('#janus_content').css('.sizeselect-wrapper_71limk').css('.red-price-wrapper.reduced.red_price_wrapper_2dpi5mv')
      self.store_2_price = products.first.children.text.delete("^0-9").to_f
    else
      self.store_2_price = nil
    end
  end

  def scrape_product_price_3
    if self.store_3_name?
      link = "#{self.store_3_link}"
      html = open(link)
      doc = Nokogiri::HTML(html)
      products = doc.css('.product-details__product-wrapper').css('.buy-area__price-wrapper').css('.buy-area__current-price')
      self.store_3_price = products.first.children.text.delete("^0-9").to_f
    else
      self.store_3_price = nil
    end
  end

  def set_best_price
    arr = [store_1_price, store_2_price, store_3_price].compact
    self.best_price = arr.min
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :new, :create, :edit, :update]

  def show
    @product = Product.friendly.find(params[:id])
    add_breadcrumb 'Hem', :root_path
    add_breadcrumb "#{@product.primary_category.name}", category_path(@product.primary_category)
    add_breadcrumb "#{@product.brand.name}", "/#{@product.brand.name}"
    add_breadcrumb @product.name
  end

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully added' }
        format.json { render :index, status: :created }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @product = Product.find_by_slug(params[:id])

  end

  def update
    @categories = Category.all
    @product = Product.find_by_slug(params[:id])
    if @product.primary_category_id?
      @primary_category = @categories.find_by_id(@product.primary_category_id)
      @product.primary_category_name = @primary_category.slug
    end
    if @product.secondary_category_id?
      @secondary_category = @categories.find_by_id(@product.secondary_category_id)
      @product.secondary_category_name = @secondary_category.slug
    end
    if @product.third_category_id?
      @third_category = @categories.find_by_id(@product.third_category_id)
      @product.third_category_name = @third_category.slug
    end
    respond_to do |format|
      if @product.update product_params
        format.html { redirect_to edit_product_path(@product), notice: 'Product edited!' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find_by_slug(params[:id])
    if @product.destroy
      flash[:notice] = "Product deleted"
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "Något gick fel"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :brand_id, :primary_category_id, :secondary_category_id, :third_category_id, :height, :width, :depth, :weight, :battery, :display, :touch_screen, :water_res, :memory, :os_compatible, :bluetooth, :wi_fi, :apps, :nfc, :voice_control, :phone_call, :music, :gps, :heart_rate, :barometer, :sleep_tracking, :calories, :steps, :oxygen, :golf, :cycling, :swimming, :store_1_name, :store_1_link, :store_1_price, :store_2_name, :store_2_link, :store_2_price, :store_3_name, :store_3_link, :store_3_price, :active, :avatar)
  end
end

app/views/products/_products.html.erb
<% @products.each do |product| %>
  <% cache product do %>
    <div id='product-<%= product.id %>'>
      <%= link_to product_path(product) do %>
      <div class='product-card'>
        <div class='card-header'>
          <div class='card-product-name'><%= product.name %></div>
        </div>
        <div class='card-image'>
          <%= image_tag(product.avatar, alt: "#{product.name}") if product.avatar.attached? %>
        </div>
        <div class='card-content'>
          <%= product.best_price %> kr
        </div>
      </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<h3>Edit products</h3>
<div class='standard-form'>
  <%= form_for @product do |f| %>
    <% if @product.errors.any? %>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <% end %>
    <%= f.label :name, 'Name', class: 'form-text' %>
    <%= f.text_field :name, value: @product.name %><br>
    <%= f.label :brand_id, 'Brand', class: 'form-text' %>
    <%= f.collection_select(:brand_id, Brand.all, :id, :name, { include_blank: true, selected: @product.brand_id }, { class: 'input-medium' }) %><br>
    <%= f.label :primary_category_id, 'Primary Category', class: 'form-text' %>
    <%= f.collection_select(:primary_category_id, Category.all, :id, :name, { include_blank: true, selected: @product.primary_category_id }, { class: 'input-medium' }) %><br>
    <%= f.label :secondary_category_id, 'Secondary Category', class: 'form-text' %>
    <%= f.collection_select(:secondary_category_id, Category.all, :id, :name, { include_blank: true, selected: @product.secondary_category_id }, { class: 'input-medium' }) %><br>
    <%= f.label :third_category_id, 'Third Category(bäst i test)', class: 'form-text' %>
    <%= f.collection_select(:third_category_id, Category.all, :id, :name, { include_blank: true, selected: @product.third_category_id }, { class: 'input-medium' }) %><br>
    <h3>Allmänt</h3>
    <%= f.label :height, 'Höjd', class: 'form-text' %>
    <%= f.text_field :height, value: @product.height, style: 'width: 80%' %><br>
    <%= f.label :width, 'Bredd', class: 'form-text' %>
    <%= f.text_field :width, value: @product.width, style: 'width: 80%' %><br>
    <%= f.label :depth, 'Djup', class: 'form-text' %>
    <%= f.text_field :depth, value: @product.depth, style: 'width: 80%' %><br>
    <%= f.label :weight, 'Vikt', class: 'form-text' %>
    <%= f.text_field :weight, value: @product.weight, style: 'width: 80%' %><br>
    <%= f.label :battery, 'Batteritid', class: 'form-text' %>
    <%= f.text_field :battery, value: @product.battery, style: 'width: 80%' %><br>
    <%= f.label :display, 'Skärm', class: 'form-text' %>
    <%= f.text_field :display, value: @product.display, style: 'width: 80%' %><br>
    <%= f.label :touch_screen, 'Pekskärm', class: 'form-text' %>
    <%= f.select :touch_screen, options_for_select([['yes', true], ['No', false]], selected: @product.touch_screen), style: 'width: 80%' %><br>
    <%= f.label :water_res, 'Vattentålig', class: 'form-text' %>
    <%= f.text_field :water_res, value: @product.water_res, style: 'width: 80%' %><br>
    <%= f.label :memory, 'Lagring', class: 'form-text' %>
    <%= f.text_field :memory, value: @product.memory, style: 'width: 80%' %><br>

    <h3>Smarta funktioner</h3>
    <%= f.label :os_compatible, 'OS-kompatibilitet', class: 'form-text' %>
    <%= f.text_field :os_compatible, value: @product.os_compatible, style: 'width: 80%' %><br>
    <%= f.label :bluetooth, 'Bluetooth', class: 'form-text' %>
    <%= f.select :bluetooth, options_for_select([['yes', true], ['No', false]], selected: @product.bluetooth), style: 'width: 80%' %><br>
    <%= f.label :wi_fi, 'Wi-Fi', class: 'form-text' %>
    <%= f.select :wi_fi, options_for_select([['yes', true], ['No', false]], selected: @product.wi_fi), style: 'width: 80%' %><br>
    <%= f.label :apps, 'Appar', class: 'form-text' %>
    <%= f.text_field :apps, value: @product.apps, style: 'width: 80%' %><br>
    <%= f.label :nfc, 'Nfc', class: 'form-text' %>
    <%= f.select :nfc, options_for_select([['yes', true], ['No', false]], selected: @product.nfc), style: 'width: 80%' %><br>
    <%= f.label :voice_control, 'Röststyrning', class: 'form-text' %>
    <%= f.select :voice_control, options_for_select([['yes', true], ['No', false]], selected: @product.voice_control), style: 'width: 80%' %><br>
    <%= f.label :phone_call, 'Telefonsamtal', class: 'form-text' %>
    <%= f.select :phone_call, options_for_select([['yes', true], ['No', false]], selected: @product.phone_call), style: 'width: 80%' %><br>
    <%= f.label :music, 'Musik', class: 'form-text' %>
    <%= f.select :music, options_for_select([['yes', true], ['No', false]], selected: @product.music), style: 'width: 80%' %><br>

    <h3>Hälsa och fitness</h3>
    <%= f.label :gps, 'Gps', class: 'form-text' %>
    <%= f.select :gps, options_for_select([['yes', true], ['No', false]], selected: @product.gps), style: 'width: 80%' %><br>
    <%= f.label :heart_rate, 'Pulsmätare', class: 'form-text' %>
    <%= f.select :heart_rate, options_for_select([['yes', true], ['No', false]], selected: @product.heart_rate), style: 'width: 80%' %><br>
    <%= f.label :barometer, 'Barometer', class: 'form-text' %>
    <%= f.select :barometer, options_for_select([['yes', true], ['No', false]], selected: @product.barometer), style: 'width: 80%' %><br>
    <%= f.label :sleep_tracking, 'Sömn', class: 'form-text' %>
    <%= f.select :sleep_tracking, options_for_select([['yes', true], ['No', false]], selected: @product.sleep_tracking), style: 'width: 80%' %><br>
    <%= f.label :calories, 'Kalorier', class: 'form-text' %>
    <%= f.select :calories, options_for_select([['yes', true], ['No', false]], selected: @product.calories), style: 'width: 80%' %><br>
    <%= f.label :steps, 'Stegräkning', class: 'form-text' %>
    <%= f.select :steps, options_for_select([['yes', true], ['No', false]], selected: @product.steps), style: 'width: 80%' %><br>
    <%= f.label :oxygen, 'Syremätning', class: 'form-text' %>
    <%= f.select :oxygen, options_for_select([['yes', true], ['No', false]], selected: @product.oxygen), style: 'width: 80%' %><br>
    <%= f.label :golf, 'Golf', class: 'form-text' %>
    <%= f.select :golf, options_for_select([['yes', true], ['No', false]], selected: @product.golf), style: 'width: 80%' %><br>
    <%= f.label :cycling, 'Cykling', class: 'form-text' %>
    <%= f.select :cycling, options_for_select([['yes', true], ['No', false]], selected: @product.cycling), style: 'width: 80%' %><br>
    <%= f.label :swimming, 'Simning', class: 'form-text' %>
    <%= f.select :swimming, options_for_select([['yes', true], ['No', false]], selected: @product.swimming), style: 'width: 80%' %><br>

    <h3>Bild</h3>
    <%= f.label :avatar, 'Bild', class: 'form-text' %>
    <%= f.file_field :avatar, value: @product.avatar %><br>
    <%= image_tag(@product.avatar, width: 200) if @product.avatar.attached? %><br>

    <h3>Affiliate</h3>
    <%= f.label :store_1_name, 'Butik Netonnet namn', class: 'form-text' %>
    <%= f.select :store_1_name, options_for_select(Product::STORE_OPTIONS, { selected: @product.store_1_name, include_blank: '-- Välj --' }), required: true, class: 'form-text' %><br>
    <%= f.label :store_1_link, 'Butik Netonnet länk', class: 'form-text' %>
    <%= f.text_field :store_1_link, value: @product.store_1_link %><br>
    <%= f.label :store_1_price, 'Butik Netonnet pris', class: 'form-text' %>
    <%= f.text_field :store_1_price, value: @product.store_1_price %> <br><br>

    <%= f.label :store_2_name, 'Butik Sportamore namn', class: 'form-text' %>
    <%= f.select :store_2_name, options_for_select(Product::STORE_OPTIONS), { include_blank: '-- Välj --' }, class: 'form-text' %><br>
    <%= f.label :store_2_link, 'Butik Sportamore länk(Tradedoubler)', class: 'form-text' %>
    <%= f.text_field :store_2_link, value: @product.store_2_link %><br>
    <%= f.label :store_2_price, 'Butik Sportamore pris', class: 'form-text' %>
    <%= f.text_field :store_2_price, value: @product.store_2_price %> <br><br>

    <%= f.label :store_3_name, 'Butik Cdon namn', class: 'form-text' %>
    <%= f.select :store_3_name, options_for_select(Product::STORE_OPTIONS), { include_blank: '-- Välj --' }, class: 'form-text' %><br>
    <%= f.label :store_3_link, 'Butik Cdon länk(Tradedoubler)', class: 'form-text' %>
    <%= f.text_field :store_3_link, value: @product.store_3_link %><br>
    <%= f.label :store_3_price, 'Butik Cdon pris', class: 'form-text' %>
    <%= f.text_field :store_3_price, value: @product.store_3_price %> <br><br>

    <h3>Aktiv</h3>
    <%= f.label :active, 'Kryssa i för att aktivera', class: 'form-text' %>
    <%= f.check_box :active, value: true %><br><br>

    <%= f.submit 'Edit', class: 'add-button' %>
  <% end %>
  <br>
  <%= link_to 'Cancel', products_path, class: 'cancel-button' %>
</div>

app/views/products/index.html.erb
<h3>Add or edit products on this page</h3>
<%= link_to 'Add product', new_product_path, class: 'add-button' %>
<div class="item-container">
  <% @products.each do |product| %>
    <div class='item-box'>
      <%= product.id %>
      <%= product.name %>
      <%= link_to 'Edit', edit_product_path(product), class: 'reply-button' %><%= link_to 'Delete', product_path(product), data: { confirm: 'Are you sure?' }, method: :delete, class: 'add-button' %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class=product-header>
  <h1><%= @product.name %></h1>
  <div class='breadcrumb-holder'>
       <%= render_breadcrumbs separator: ' > ' %>
   </div>
</div>
<div class='product-holder'>
  <div class='product-card-holder'>
    <%= image_tag(@product.avatar, alt: "#{@product.name}") if @product.avatar.attached? %>
  </div>
  <div class='product-card-holder'>
    <div class='product-compare-holder'>
      <div class='compare-header'>
        Prisjämförelse
      </div>
      <div class='compare-content'>
        <div class='compare-name'>
          <%= @product.store_1_name %>
        </div>
        <div class='compare-price'>
          <%= @product.store_1_price %>
        </div>
        <div class='compare-link'>
          <%= link_to 'Till butik', "#{@product.store_1_link}" %>
        </div>
      </div>
      <p style='font-size: 0.7em'><span style='color: green;'>✓</span> Endast pålitliga återförsäljare</p>
      <div class='product-facts'>
        <h4>Snabbfakta</h4>
        <div class='product-facts-holder'>
          <div class='facts-content'>
            Märke
          </div>
          <div class='facts-content'>
            <%= link_to "#{@product.brand.name}", brand_path(@product.brand) %>
          </div>
        </div>
        <div class='product-facts-holder'>
          <div class='facts-content'>
            Pulsmätning
          </div>
          <div class='facts-content'>
            <%= @product.heart_rate %>
          </div>
        </div>
        <div class='product-facts-holder'>
          <div class='facts-content'>
            Batteritid
          </div>
          <div class='facts-content'>
            <%= @product.battery %>h
          </div>
        </div>
        <div class='product-facts-holder'>
          <div class='facts-content'>
            Telefonsamtal
          </div>
          <div class='facts-content'>
            <% if @product.phone_call == true %>
              Ja
            <% else %>
              Nej
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% if @product.store_2_name? %>
      <%= @product.store_2_name %><%= @product.store_2_price %><%= link_to 'Till butik', "#{@product.store_2_link}" %><br>
    <% end %>
    <% if @product.store_3_name? %>
      <%= @product.store_3_name %><%= @product.store_3_price %><%= link_to 'Till butik', "#{@product.store_3_link}" %><br>
    <% end %>
  </div>
</div>
<div class='specs-holder'>
  <div class='specs-container'>
    <div class='specs-header'>
      <h4>Allmänt</h4>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Höjd
      </div>
      <div class='specs-amount'>
        <%= @product.height %>
      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Bredd
      </div>
      <div class='specs-amount'>
        <%= @product.width %>
      </div>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Djup
      </div>
      <div class='specs-amount'>
        <%= @product.depth %>
      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Vikt
      </div>
      <div class='specs-amount'>
        <%= @product.weight %>
      </div>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Display
      </div>
      <div class='specs-amount'>
        <%= @product.display %>
      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Pekskärm
      </div>
      <div class='specs-amount'>
        <% if @product.touch_screen == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Vattentålig
      </div>
      <div class='specs-amount'>
        <%= @product.water_res %>
      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Minne
      </div>
      <div class='specs-amount'>
        <%= @product.memory %>
      </div>
    </div>
  </div>
  <div class='specs-container'>
    <div class='specs-header'>
      <h4>Smarta funktioner</h4>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Smartphone kompatibel
      </div>
      <div class='specs-amount'>
        <%= @product.os_compatible %>
      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Bluetooth
      </div>
      <div class='specs-amount'>
        <% if @product.bluetooth == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Wi-Fi
      </div>
      <div class='specs-amount'>
        <% if @product.wi_fi == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Appar
      </div>
      <div class='specs-amount'>
        <%= @product.apps %>
      </div>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        NFC (Near Field Communication)
      </div>
      <div class='specs-amount'>
        <% if @product.nfc == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Röststyrning
      </div>
      <div class='specs-amount'>
        <% if @product.voice_control == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Musik
      </div>
      <div class='specs-amount'>
        <% if @product.music == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
  </div>
  <div class='specs-container'>
    <div class='specs-header'>
      <h4>Hälsa och fitness</h4>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        GPS
      </div>
      <div class='specs-amount'>
        <% if @product.gps == true %>
          Ja
        <% else %>
          Nej
        <% end %>

      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Barometer (Höjdmätare)
      </div>
      <div class='specs-amount'>
        <% if @product.barometer == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Sömnövervakning
      </div>
      <div class='specs-amount'>
        <% if @product.sleep_tracking == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Kalorier
      </div>
      <div class='specs-amount'>
        <% if @product.calories == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Stegräknare
      </div>
      <div class='specs-amount'>
        <% if @product.steps == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Syremätning
      </div>
      <div class='specs-amount'>
        <% if @product.oxygen == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Golf kompatibel
      </div>
      <div class='specs-amount'>
        <% if @product.golf == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table'>
      <div class='specs-feature'>
        Cykel kompatibel
      </div>
      <div class='specs-amount'>
        <% if @product.cycling == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
    <div class='specs-table-white'>
      <div class='specs-feature'>
        Kompatibel för simning
      </div>
      <div class='specs-amount'>
        <% if @product.swimming == true %>
          Ja
        <% else %>
          Nej
        <% end %>
      </div>
    </div>
  </div>
</div>