config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, except: [:registrations]
    as :admin do
      get 'admins/edit' => 'admins/registrations#edit', as: 'edit_admin_registration'
      put 'admins' => 'admins/registrations#update', as: 'admin_registration'
    end
    devise_scope :admin do
      authenticated :admin do
        root to: 'administrations#index', as: :authenticated_root
      end
    end

    root controller: :index, action: :index

    get 'kontakta', to: 'kontaktas#index'

    get 'blogg', to: 'articles#all'

    resources :articles, controller: 'articles', as: 'articles', only: [:show, :new, :create, :edit, :update, :index, :destroy]

    resources :kategorier, controller: 'categories', as: 'categories', only: [:show, :new, :create, :edit, :update, :index, :destroy]

    resources :brands, controller: 'brands', only: [:new, :create, :edit, :update, :index, :destroy]

    resources :produkter, controller: 'products', as: 'products', only: [:new, :create, :edit, :update, :index, :destroy]

    get '/produkter/:id', to: 'products#show'

    resources :brands, controller: 'brands', as: 'brands', only: [:show], path: ''

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="sv">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>Pulsklockan</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
  </head>

  <body>
		<div class="nav">
      <input type="checkbox" id="nav-check">
      <div class="nav-header">
        <a class="nav-title" href="/" id="logo-new">Pulsklockan.com</a>
      </div>
      <div class="nav-btn">
        <label for="nav-check">
          <span></span>
          <span></span>
          <div class='menu'>Meny</div>
        </label>
      </div>

      <div class="nav-links">
        <a href="/kategorier/pulsklockor">Pulsklockor</a>
        <a href="/kategorier/aktivitetsarmband">Aktivitetsarmband</a>
        <a href="/kategorier/smartklockor">Smarta klockor</a>
        <a href="/kategorier/bast-i-test">Bäst i test</a>
        <% if admin_signed_in? %>
          <%= link_to "Admin", admin_session_path %>
          <%= link_to "Log out", destroy_admin_session_path, {method: :delete} %>
        <% end %>
      </div>
    </div>
    <% if notice %>
      <div id="notice-wrapper" >
        <p class="notice"><%= notice %></p>
      </div>
    <% elsif alert %>
      <div id='alert-wrapper' >
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <div class='container-main'>
      <%= yield %>
    </div>
    <div class='footer'>
      <div class='footer-grid'>
        <div class='footer-container'>
          <h3>Populära märken</h3>
          <p><%= link_to 'Fitbit', "/Fitbit" %></p>
          <p><%= link_to 'Garmin', "/Garmin" %></p>
          <p><%= link_to 'Apple', "/Apple-watch" %></p>
          <p><%= link_to 'Suunto', "/Suunto" %></p>
        </div>
        <div class='footer-container'>
          <h3>Vilka är vi?</h3>
          <p>Vi är en jämförelsesajt för pulsklockor, aktivitetsarmband och smarta klockor. Vi är en opartisk aktör vars främsta mål är att du ska enkelt hitta den produkt du söker till bästa pris.</p>
        </div>
        <div class='footer-container'>
          <h3>Information</h3>
          <p><%= link_to 'Kontakta oss', "/kontakta" %></p>
          <p><%= link_to 'Blogg', "/blogg" %></p>
          <p><%= link_to 'Pulsklockor', "/pulsklockor" %></p>
          <p><%= link_to 'Akitivetsarmband', "/aktivitetsarmband" %></p>
          <p><%= link_to 'Smartklockor', "/smartklockor" %></p>
          <p><%= link_to 'Bäst i test', "/bast-i-test" %></p>
        </div>
      </div>
    </div>
  </body>
</html>